"""Docker & host management catalog entries."""

CATALOG: list[dict] = [
    {
        "id": "portainer",
        "name": "Portainer CE",
        "category": "Docker & host management",
        "pitch": "Deeper stack/volume/network management than the control panel's app-specific container controls.",
        "image": "portainer/portainer-ce",
        "tag": "lts",
        "ports": {"9443/tcp": 9443},
        "volumes": {"catalog_portainer_data": {"bind": "/data", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~80MB RAM",
        "doc_url": "https://github.com/portainer/portainer",
        "caveat": "Overlaps with the control panel's own docker.sock access - different job (general admin vs. app-specific actions), not redundant, but both can restart the same container.",
        "docker_sock": True,
    },
    {
        "id": "filebrowser",
        "name": "Filebrowser",
        "category": "Docker & host management",
        "pitch": "A plain web file manager scoped to the media/config directories - upload, rename, preview without a terminal.",
        "image": "filebrowser/filebrowser",
        "tag": "latest",
        "ports": {"80/tcp": 8082},
        "volumes": {"catalog_filebrowser_data": {"bind": "/database", "mode": "rw"}},
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~25MB RAM",
        "doc_url": "https://github.com/filebrowser/filebrowser",
        "caveat": "Installed with no media/config bind mount by default - add one manually before use, scoped as tightly as you're comfortable with.",
    },
    {
        "id": "caddy",
        "name": "Caddy",
        "category": "Docker & host management",
        "pitch": "Reverse proxy with fully automatic HTTPS - two lines of config gets every service in this catalog a real certificate instead of a bare IP:port.",
        "image": "caddy",
        "tag": "latest",
        "ports": {"80/tcp": 80, "443/tcp": 443},
        "volumes": {
            "catalog_caddy_data": {"bind": "/data", "mode": "rw"},
            "catalog_caddy_config": {"bind": "/config", "mode": "rw"},
        },
        "environment": {},
        "cap_add": [],
        "devices": [],
        "footprint": "~15MB RAM",
        "doc_url": "https://caddyserver.com/docs/",
        "caveat": "Installed with a blank Caddyfile - add site blocks for each service you want proxied.",
    },
]
