# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-queue-status -f
complete -c stack-queue-status -d 'Show every app\'s download queue with a live-measured speed and ETA'
