# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-pkg-update -f
complete -c stack-pkg-update -d 'Run pacman/AUR system update (confirmation-gated)'
