# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-watchstate-import-now -f
complete -c stack-watchstate-import-now -d 'Queue an out-of-schedule WatchState import from Plex'
