# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-service-failed -f
complete -c stack-service-failed -d 'List failed systemd units (system and user)'
