# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-tmdb-audit -f
complete -c stack-tmdb-audit -d 'Audit TMDB links in a Plex library (Movies by default)'
