# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-perms-check -f
complete -c stack-perms-check -d 'Find config files unreadable by group/other (won\'t be backed up)'
