# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-kernel-check -f
complete -c stack-kernel-check -d 'Check for a pending kernel-update reboot'
