# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-cleanuparr-instances -f
complete -c stack-cleanuparr-instances -d 'Which *arr apps Cleanuparr has an actual connected instance for'
