# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-uptime-report -f
complete -c stack-uptime-report -d 'Show uptime, load average, and last-boot cleanliness'
