# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-mem-pressure -f
complete -c stack-mem-pressure -d 'Show kernel pressure-stall info for memory/CPU/IO'
