# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-claude-home -f
complete -c stack-claude-home -d 'Launch Claude in the ~/Claude workspace with full permissions'
