# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-file-backup -f
complete -c stack-file-backup -d 'Create a .bak copy of a file'
