# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-ssh-doctor -f
complete -c stack-ssh-doctor -d 'Check SSH setup health (keys, known_hosts, agent)'
