# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-mount-health -f
complete -c stack-mount-health -d 'Check every known FUSE mountpoint resolves cleanly'
