# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-zombie-check -f
complete -c stack-zombie-check -d 'Check for zombie/defunct processes'
