# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-log-levels -f
complete -c stack-log-levels -n 'test (count (commandline -opc)) -eq 1' -d 'reset'
complete -c stack-log-levels -d 'Check (or reset) every Servarr app\'s log level'
