# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-oom-check -f
complete -c stack-oom-check -d 'List containers Docker has recorded an OOM-kill for'
