# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-watchstate-history -f
complete -c stack-watchstate-history -n 'test (count (commandline -opc)) -eq 1' -d 'title'
complete -c stack-watchstate-history -d 'Watch history WatchState recorded, optionally filtered to a title'
