# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-journal-errors -f
complete -c stack-journal-errors -d 'Summarize error-level journal entries since last boot'
