# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-nzbdav-dedup-check -f
complete -c stack-nzbdav-dedup-check -d 'Verify NzbDAV duplicate-nzb-behavior is still mark-failed'
