# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-restart-all -f
complete -c stack-restart-all -d 'Restart the whole stack (confirms first)'
