# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-version -f
complete -c stack-version -d 'README\'s declared version + live container count'
