# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-nzbdav-delete-failures -f
complete -c stack-nzbdav-delete-failures -d 'Delete all Failed entries from NzbDAV history'
