# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-help -f
complete -c stack-help -d 'List all stack-* terminal commands for the media stack'
