# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-flatpak-updates -f
complete -c stack-flatpak-updates -d 'List (or apply) pending Flatpak updates'
