# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-timer-status -f
complete -c stack-timer-status -d 'Check stack-*.timer units are enabled and their last run succeeded'
