# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-nzbdav-queue -f
complete -c stack-nzbdav-queue -d 'Show NzbDAV\'s current Usenet download queue'
