# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-pkg-orphans -f
complete -c stack-pkg-orphans -d 'List (or remove) orphaned pacman packages'
