# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-aur-audit -f
complete -c stack-aur-audit -d 'Check installed packages against Arch security advisories (or list AUR packages)'
