# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-watchstate-status -f
complete -c stack-watchstate-status -d 'WatchState sync state, tracked items, import schedule'
