# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-disk-free -f
complete -c stack-disk-free -n 'test (count (commandline -opc)) -eq 1' -d 'warn-pct, default 80'
complete -c stack-disk-free -n 'test (count (commandline -opc)) -eq 2' -d 'crit-pct, default 90'
complete -c stack-disk-free -d 'Show disk free space with warn/critical thresholds'
