# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-disk-health -f
complete -c stack-disk-health -d 'Show SMART health summary for all physical disks'
