# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-firewall-status -f
complete -c stack-firewall-status -d 'Show active nftables rules and listening ports'
