# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-git-status-all -f
complete -c stack-git-status-all -d 'git status --short across every repo under ~/Claude'
