# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-nzbdav-history -f
complete -c stack-nzbdav-history -d 'Show NzbDAV\'s recent download history (completed/failed)'
