# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-image-check -f
complete -c stack-image-check -d 'Check digest/exact-version-pinned images for a newer registry digest'
