# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-container -f
complete -c stack-container -n 'test (count (commandline -opc)) -eq 1' -a 'restart stop start'
complete -c stack-container -n 'test (count (commandline -opc)) -eq 2' -a "(__stack_containers)"
complete -c stack-container -d 'Restart/stop/start a single stack container'
