# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-cleanuparr-strikes -f
complete -c stack-cleanuparr-strikes -d 'Show recent Cleanuparr strikes'
