# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-alacritty-theme -f
complete -c stack-alacritty-theme -d 'Switch the active Alacritty theme (aliases.toml aware)'
