# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-pkg-updates -f
complete -c stack-pkg-updates -d 'List pending pacman and AUR package updates'
