# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-top -f
complete -c stack-top -n 'test (count (commandline -opc)) -eq 1' -a 'cpu mem'
complete -c stack-top -d 'Show top containers by CPU or memory usage'
