# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-cron-list -f
complete -c stack-cron-list -d 'List all scheduled jobs: system timers, user timers, and crontabs'
