# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-docker-disk-usage -f
complete -c stack-docker-disk-usage -d 'Show Docker disk usage broken down by category'
