# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-arr-import-backlog -f
complete -c stack-arr-import-backlog -d 'Show only items waiting on import across radarr/sonarr, grouped by release'
