# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-nzbdav-stats -f
complete -c stack-nzbdav-stats -d 'Show aggregate NzbDAV queue/history stats'
