# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-status -f
complete -c stack-status -d 'Show live state/health of every media-stack container'
