# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-disk-config-sizes -f
complete -c stack-disk-config-sizes -d 'Per-app config/ directory size, largest first'
