# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-claude-full-backup -f
complete -c stack-claude-full-backup -d 'Full ~/Claude tar.zst backup to Dropbox (dated, no excludes)'
