# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-pkg-cleanup -f
complete -c stack-pkg-cleanup -d 'Remove orphaned packages via pacman'
