# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-resource-check -f
complete -c stack-resource-check -d 'List containers missing mem_limit/cpus'
