# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-journal-size -f
complete -c stack-journal-size -l vacuum-size -r
complete -c stack-journal-size -d 'Show (or vacuum) systemd-journald disk usage'
