# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-notify-test -f
complete -c stack-notify-test -d 'Send a test notification to the stack Discord webhook'
