# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-pkg-clean-cache -f
complete -c stack-pkg-clean-cache -n 'test (count (commandline -opc)) -eq 1' -d 'keep-N, default 3'
complete -c stack-pkg-clean-cache -d 'Vacuum pacman cache, keeping the last N versions per package'
