# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-reboot-check -f
complete -c stack-reboot-check -d 'Check whether this host needs a reboot'
