# GENERATED by scripts/fish-completions-generate.py - do not edit.
# Regenerate after changing the function: scripts/fish-completions-generate.py
complete -c stack-pkg-history -f
complete -c stack-pkg-history -n 'test (count (commandline -opc)) -eq 1' -d 'N, default 20'
complete -c stack-pkg-history -d 'Show recent pacman transaction log entries'
