#!/usr/bin/env python3
"""Generate fish tab completions for every stack-* command, from the
functions themselves.

Hand-writing 200 completion files guarantees drift: the day someone adds a
`--dry-run` flag to a command, its completion silently stops describing
reality and nobody notices, because a missing completion is invisible.
So this reads the source of truth instead - each function's own argparse
call, its `contains` guards, and its `# Usage:` header - and regenerates
the whole completions directory from it.

Three signals, in descending trust:

  1. `argparse a b= c -- $argv`  - the flags the function actually parses.
     A trailing `=` means the flag takes a value, which fish needs to know
     (`-r`) or it will offer flags where a value belongs.
  2. `contains -- $argv[N] x y z` - the positional allow-list the function
     enforces. This is the strongest possible completion source: if the
     function rejects everything else, these are exactly the valid values.
  3. `# Usage: name <a|b|c> [d|e]` - the header comment, for positionals
     with no runtime guard (an id, a URL, a limit). Alternation groups
     become completions; free-form placeholders become a description only.

Anything not covered by those three gets `complete -f` (no file completion)
and a description, which is still better than fish's default of offering
every filename in the current directory to a command that takes a movie id.

Usage:
    fish-completions-generate.py [--check] [--repo-dir DIR]

    --check  exit 1 if the generated output differs from what is on disk,
             without writing anything. This is what the gate test runs.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_REPO_DIR = Path(__file__).resolve().parent.parent / "fish-functions"
COMPLETIONS_DIRNAME = "completions"

HEADER = (
    "# GENERATED by scripts/fish-completions-generate.py - do not edit.\n"
    "# Regenerate after changing the function: scripts/fish-completions-generate.py\n"
)

# Placeholder names that are free-form input, not a closed set. Listing them
# keeps the generator from emitting a literal completion for "<movie-id>".
FREE_FORM = re.compile(r"^[a-z0-9-]*(id|url|name|limit|lines|days|text|slug|path|file|n|gb|hours)$", re.I)


def _description(text: str) -> str:
    """The function's own --description, which fish shows beside the command."""
    m = re.search(r"--description\s+(['\"])(.*?)\1(?:\s|$)", text, re.S)
    if not m:
        return ""
    # Fish escapes a literal quote by doubling it inside single quotes.
    return m.group(2).replace("''", "'").replace("\\'", "'").strip()


def _flags(text: str) -> list[tuple[str, bool]]:
    """(flag, takes_value) from the function's own argparse call."""
    m = re.search(r"argparse\s+(.*?)\s+--\s+\$argv", text, re.S)
    if not m:
        return []
    out: list[tuple[str, bool]] = []
    for raw in re.findall(r"'([^']+)'|\"([^\"]+)\"|(\S+)", m.group(1)):
        token = raw[0] or raw[1] or raw[2]
        if token.startswith("-"):
            continue
        # argparse specs look like `name`, `name=`, or `n/name`.
        takes_value = token.endswith("=")
        token = token.rstrip("=")
        name = token.split("/")[-1]
        if name and name not in (f for f, _ in out):
            out.append((name, takes_value))
    return out


def _guard_choices(text: str) -> dict[int, list[str]]:
    """{position: [allowed values]} from `contains -- $argv[N] a b c` guards."""
    out: dict[int, list[str]] = {}
    for m in re.finditer(r"contains\s+--\s+\$argv\[(\d+)\]\s+([^\n;]+)", text):
        pos = int(m.group(1))
        values = [v for v in m.group(2).split() if re.fullmatch(r"[a-z0-9_-]+", v)]
        if values:
            out.setdefault(pos, [])
            for v in values:
                if v not in out[pos]:
                    out[pos].append(v)
    return out


def _usage_positionals(text: str, command: str) -> list[tuple[str, list[str]]]:
    """[(label, choices)] per positional, parsed from the `# Usage:` header."""
    m = re.search(rf"^#\s*Usage:\s*{re.escape(command)}\s*(.*)$", text, re.M)
    if not m:
        return []
    out: list[tuple[str, list[str]]] = []
    for token in re.findall(r"<([^>]+)>|\[([^\]]+)\]", m.group(1)):
        body = token[0] or token[1]
        if body.startswith("-"):  # a flag, already covered by argparse
            continue
        body = body.replace("...", "").strip()
        if "|" in body:
            choices = [c.strip() for c in body.split("|") if re.fullmatch(r"[a-z0-9_-]+", c.strip())]
            out.append((body, choices))
        else:
            out.append((body, []))
    return out


# A fourth signal, narrower than the three above: values a function holds in
# a local list rather than a `contains` guard, and values only the running
# host knows. Each entry is (position, completion-source). A '(' prefix makes
# it a fish command substitution, evaluated at tab time, not generation time.
EXTRA_POSITIONALS: dict[str, list[tuple[int, str]]] = {
    # `set -l tasks a b c \` continuation lines, not a guard - the function
    # validates against this list but the regex above only sees one line.
    "stack-plex-butler": [(1, "(__stack_plex_butler_tasks)")],
    # Container names change with docker-compose.yml; reading them at tab
    # time means a new service is completable the moment it is up.
    "stack-container": [(2, "(__stack_containers)")],
}


def _nth(pos: int) -> str:
    """Condition matching "the caller is typing positional argument `pos`".

    `commandline -opc` is the tokens already committed, so exactly one of
    them (the command) means argument 1 is being typed now. Preferred over
    __fish_is_nth_token, which counts the token under the cursor and fired
    one position early in fish 4.8.1 - `stack-arr radarr <TAB>` offered app
    names again instead of actions.
    """
    return f"test (count (commandline -opc)) -eq {pos}"


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", r"\'")


def render(path: Path) -> str:
    """The completion file for one function."""
    command = path.stem
    text = path.read_text()
    desc = _description(text)
    flags = _flags(text)
    guards = _guard_choices(text)
    positionals = _usage_positionals(text, command)

    takes_path = any("path" in label or "file" in label for label, _ in positionals)

    lines = [HEADER]
    if not takes_path:
        # Without this fish offers every filename in $PWD to a command that
        # wants a movie id.
        lines.append(f"complete -c {command} -f\n")

    for flag, takes_value in flags:
        bits = [f"complete -c {command}", f"-l {flag}"]
        if takes_value:
            bits.append("-r")
        if flag in ("yes", "y"):
            bits.append("-d 'Skip the confirmation prompt'")
        elif flag == "dry-run":
            bits.append("-d 'Report what would happen, change nothing'")
        lines.append(" ".join(bits) + "\n")

    # Positional completions. A runtime guard beats the Usage header: the
    # guard is what actually rejects input.
    extras = dict(EXTRA_POSITIONALS.get(command, []))
    n = max([*guards.keys(), *extras.keys(), len(positionals)], default=0)
    for pos in range(1, n + 1):
        if pos in extras:
            lines.append(f"complete -c {command} -n '{_nth(pos)}' -a \"{extras[pos]}\"\n")
            continue
        choices = guards.get(pos)
        label = positionals[pos - 1][0] if pos <= len(positionals) else ""
        if not choices and pos <= len(positionals):
            choices = positionals[pos - 1][1]
        cond = f"-n '{_nth(pos)}'"
        if choices:
            lines.append(f"complete -c {command} {cond} -a '{_escape(' '.join(choices))}'\n")
        elif label and not FREE_FORM.fullmatch(label):
            lines.append(f"complete -c {command} {cond} -d '{_escape(label)}'\n")

    if desc:
        lines.append(f"complete -c {command} -d '{_escape(desc)}'\n")
    return "".join(lines)


def generate(repo_dir: Path) -> dict[str, str]:
    return {f"{p.stem}.fish": render(p) for p in sorted(repo_dir.glob("stack-*.fish"))}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-dir", type=Path, default=DEFAULT_REPO_DIR)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    out_dir = args.repo_dir / COMPLETIONS_DIRNAME
    wanted = generate(args.repo_dir)

    if args.check:
        existing = {p.name: p.read_text() for p in out_dir.glob("*.fish")} if out_dir.exists() else {}
        if existing == wanted:
            print(f"completions up to date ({len(wanted)} files)")
            return 0
        for name in sorted(set(wanted) | set(existing)):
            if name not in existing:
                print(f"  missing: {name}")
            elif name not in wanted:
                print(f"  stale:   {name}")
            elif existing[name] != wanted[name]:
                print(f"  differs: {name}")
        print("\nRun scripts/fish-completions-generate.py to regenerate.")
        return 1

    out_dir.mkdir(exist_ok=True)
    for stale in out_dir.glob("*.fish"):
        if stale.name not in wanted:
            stale.unlink()
    for name, body in wanted.items():
        (out_dir / name).write_text(body)
    print(f"wrote {len(wanted)} completion files to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
