# Generated by Django 5.1.4 on 2026-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_hash', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='LetterboxdSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_url', models.CharField(max_length=1024)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('matched', models.IntegerField(default=0)),
                ('unmatched', models.IntegerField(default=0)),
                ('added', models.IntegerField(default=0)),
                ('already', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('tv_crossover', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'letterboxd_sync_log',
            },
        ),
        migrations.CreateModel(
            name='LetterboxdTmdbCache',
            fields=[
                ('slug', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('media_type', models.CharField(default='movie', max_length=32)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'letterboxd_tmdb_cache',
            },
        ),
        migrations.CreateModel(
            name='LetterboxdTrackedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('root_folder', models.CharField(blank=True, max_length=1024, null=True)),
                ('quality_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_quality_map_json', models.TextField(blank=True, null=True)),
                ('tags_as_radarr_tags', models.BooleanField(default=False)),
                ('app', models.CharField(default='radarr', max_length=64)),
                ('sonarr_app', models.CharField(default='sonarr', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'letterboxd_tracked_list',
            },
        ),
        migrations.CreateModel(
            name='MDBListSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_url', models.CharField(max_length=1024)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('radarr_added', models.IntegerField(default=0)),
                ('radarr_already', models.IntegerField(default=0)),
                ('radarr_failed', models.IntegerField(default=0)),
                ('sonarr_added', models.IntegerField(default=0)),
                ('sonarr_already', models.IntegerField(default=0)),
                ('sonarr_failed', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mdblist_sync_log',
            },
        ),
        migrations.CreateModel(
            name='MDBListTrackedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.CharField(default='radarr', max_length=64)),
                ('sonarr_app', models.CharField(default='sonarr', max_length=64)),
                ('radarr_root_folder', models.CharField(blank=True, max_length=1024, null=True)),
                ('radarr_quality_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('sonarr_root_folder', models.CharField(blank=True, max_length=1024, null=True)),
                ('sonarr_quality_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mdblist_tracked_list',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value_json', models.TextField()),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
