#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
FISH_DIR="${HOME}/.config/fish"

# Symlink ALL functions: the stack-* commands plus the __-prefixed helpers
# they call at runtime (__arr_api, __plex_api, ...). Fish only autoloads a
# file when its command name is invoked, so __-files are never exposed as
# user commands — but they must be on the function path for the stack-*
# commands to work.
installed=0
for f in "$SCRIPT_DIR"/functions/*.fish; do
    [ -f "$f" ] || continue
    ln -sf "$f" "$FISH_DIR/functions/$(basename "$f")"
    installed=$((installed + 1))
done

# __cli_format.fish defines shared fmt_* helpers but nothing ever invokes a
# command named __cli_format, so autoload would never load it. conf.d scripts
# run at fish startup, which is exactly what a shared helper library needs.
mkdir -p "$FISH_DIR/conf.d"
ln -sf "$SCRIPT_DIR/functions/__cli_format.fish" "$FISH_DIR/conf.d/bearcave-cli-format.fish"

# bearcave-env.fish loads the stack .env (API keys, tokens) into the fish
# environment at startup so the stack-* commands can reach the services
# without exporting keys by hand. The conf.d entry is a copy with the repo
# path substituted (not a symlink or a `source` wrapper): fish 4.8.1 stack-
# overflows when a file sourced from conf.d at startup uses `read`, and
# status --current-filename is unreliable inside conf.d scripts.
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
# Remove any stale entry first: a leftover symlink would make the redirect
# write through it and truncate the checked-in loader (input == output).
rm -f "$FISH_DIR/conf.d/bearcave-env.fish"
{
    echo "# Generated by install.sh — do not edit. Loads the stack .env at startup."
    echo "set -gx BEARCAVE_REPO_DIR \"$REPO_DIR\""
    cat "$SCRIPT_DIR/conf.d/bearcave-env.fish"
} > "$FISH_DIR/conf.d/bearcave-env.fish"

# Symlink completions (optional — directory may be empty)
mkdir -p "$FISH_DIR/completions"
completions=0
for f in "$SCRIPT_DIR"/completions/*.fish; do
    [ -f "$f" ] || continue
    ln -sf "$f" "$FISH_DIR/completions/$(basename "$f")"
    completions=$((completions + 1))
done

echo "Installed $installed functions + $completions completions + conf.d env loader from fish-functions."

# ----------------------------------------------------------------------------
# Bash/zsh: guarded docker compose wrapper (landmine #3)
# ----------------------------------------------------------------------------
# Mirrors functions/docker.fish for POSIX shells: intercepts `docker compose
# ... nzbdav` recreates and routes them through scripts/nzbdav-safe-recreate.sh
# so the queue guard fires even when the recreate bypasses update-nzbdav.sh.
# Writes a snippet the user sources from .bashrc/.zshrc.
BASH_SNIPPET_DIR="${HOME}/.config/bearcave"
mkdir -p "$BASH_SNIPPET_DIR"
cat > "$BASH_SNIPPET_DIR/docker-guard.sh" <<'SNIPPET'
# Bear Cave — guarded docker compose wrapper (landmine #3: nzbdav queue).
# Source from ~/.bashrc or ~/.zshrc:  source ~/.config/bearcave/docker-guard.sh
# Routes `docker compose up|restart|... nzbdav` through the queue guard;
# queries (ps, logs, config, exec) pass through. --force skips the guard.
docker() {
    if [ "$#" -lt 2 ] || [ "$1" != compose ]; then
        command docker "$@"; return $?
    fi
    case "$2" in
        up|restart|start|stop|rm|down)
            # only gate when the service is nzbdav/nzbdav_rclone
            case " $* " in
                *" nzbdav"*|*" nzbdav_rclone"*)
                    case " $* " in
                        *" --force "*)
                            echo "[guard] --force: skipping queue guard (queued NZBs WILL be wiped)" >&2
                            # strip --force before forwarding (compose doesn't know it)
                            local _args=()
                            for _a in "$@"; do [ "$_a" != --force ] && _args+=("$_a"); done
                            command docker "${_args[@]}"; return $? ;;
                        *)
                            guard="${BEARCAVE_REPO_DIR:-$HOME/TheBearCave}/scripts/nzbdav-safe-recreate.sh"
                            if [ -x "$guard" ]; then
                                shift  # drop the leading `docker`
                                bash "$guard" "$@"
                                return $?
                            fi
                            echo "[guard] nzbdav-safe-recreate.sh not found — running unguarded" >&2
                            command docker "$@"; return $? ;;
                    esac ;;
            esac ;;
    esac
    command docker "$@"; return $?
}
SNIPPET
echo "Wrote bash/zsh docker-guard snippet to $BASH_SNIPPET_DIR/docker-guard.sh"
echo "  Source it from ~/.bashrc or ~/.zshrc:"
echo "    source $BASH_SNIPPET_DIR/docker-guard.sh"
