#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
FISH_DIR="${HOME}/.config/fish"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Refuse to install from a git worktree: install.sh symlinks into the checkout
# it runs from, so an ephemeral worktree strands every installed symlink (and
# the baked BEARCAVE_REPO_DIR) the moment it is removed. A main checkout has a
# .git directory; a worktree has a .git file pointing at the shared store.
if [ -f "$REPO_ROOT/.git" ]; then
    echo "ERROR: refusing to install from a git worktree: $REPO_ROOT" >&2
    echo "  Symlinks would point at this checkout and dangle after it is removed." >&2
    echo "  Run install.sh from the permanent main checkout instead." >&2
    exit 1
fi

# Prune stale symlinks left by previous installs (commands retired since the
# last run). Only symlinks whose target no longer exists are removed; fish's
# own files and any regular files the user keeps are left untouched.
pruned=0
for d in functions completions conf.d; do
    mkdir -p "$FISH_DIR/$d"
    while IFS= read -r link; do
        [ -z "$link" ] && continue
        rm -f "$link"
        echo "  pruned stale symlink: $link"
        pruned=$((pruned + 1))
    done < <(find "$FISH_DIR/$d" -maxdepth 1 -type l ! -exec test -e {} \; -print 2>/dev/null)
done

# Symlink ALL functions: the stack-* commands plus the __-prefixed helpers
# they call at runtime (__arr_api, __plex_api, ...). Fish only autoloads a
# file when its command name is invoked, so __-files are never exposed as
# user commands — but they must be on the function path for the stack-*
# commands to work.
installed=0
for f in "$SCRIPT_DIR"/functions/*.fish; do
    [ -f "$f" ] || continue
    ln -sf "$f" "$FISH_DIR/functions/$(basename "$f")"
    installed=$((installed + 1))
done

# __cli_format.fish defines shared fmt_* helpers but nothing ever invokes a
# command named __cli_format, so autoload would never load it. conf.d scripts
# run at fish startup, which is exactly what a shared helper library needs.
mkdir -p "$FISH_DIR/conf.d"
ln -sf "$SCRIPT_DIR/functions/__cli_format.fish" "$FISH_DIR/conf.d/bearcave-cli-format.fish"

# bearcave-env.fish loads the stack .env (API keys, tokens) into the fish
# environment at startup so the stack-* commands can reach the services
# without exporting keys by hand. The conf.d entry is a copy with the repo
# path substituted (not a symlink or a `source` wrapper): fish 4.8.1 stack-
# overflows when a file sourced from conf.d at startup uses `read`, and
# status --current-filename is unreliable inside conf.d scripts.
REPO_DIR="$REPO_ROOT"
# Remove any stale entry first: a leftover symlink would make the redirect
# write through it and truncate the checked-in loader (input == output).
rm -f "$FISH_DIR/conf.d/bearcave-env.fish"
{
    echo "# Generated by install.sh — do not edit. Loads the stack .env at startup."
    echo "set -gx BEARCAVE_REPO_DIR \"$REPO_DIR\""
    cat "$SCRIPT_DIR/conf.d/bearcave-env.fish"
} > "$FISH_DIR/conf.d/bearcave-env.fish"

# Symlink completions (optional — directory may be empty)
mkdir -p "$FISH_DIR/completions"
completions=0
for f in "$SCRIPT_DIR"/completions/*.fish; do
    [ -f "$f" ] || continue
    ln -sf "$f" "$FISH_DIR/completions/$(basename "$f")"
    completions=$((completions + 1))
done

echo "Installed $installed functions + $completions completions + conf.d env loader from fish-functions."

if [ "$pruned" -gt 0 ]; then
    echo "Pruned $pruned stale symlink(s) from $FISH_DIR."
fi

# ----------------------------------------------------------------------------
# Bash/zsh: guarded docker compose wrapper (landmine #3)
# ----------------------------------------------------------------------------
# Mirrors functions/docker.fish for POSIX shells: intercepts `docker compose
# ... nzbdav` recreates and routes them through scripts/nzbdav-safe-recreate.sh
# so the queue guard fires even when the recreate bypasses update-nzbdav.sh.
# Writes a snippet the user sources from .bashrc/.zshrc.
BASH_SNIPPET_DIR="${HOME}/.config/bearcave"
mkdir -p "$BASH_SNIPPET_DIR"
cat > "$BASH_SNIPPET_DIR/docker-guard.sh" <<'SNIPPET'
# Bear Cave — guarded docker compose wrapper (landmine #3: nzbdav queue).
# Source from ~/.bashrc or ~/.zshrc:  source ~/.config/bearcave/docker-guard.sh
# Routes `docker compose up|restart|... nzbdav` through the queue guard;
# queries (ps, logs, config, exec) pass through. --force skips the guard.
docker() {
    if [ "$#" -lt 2 ] || [ "$1" != compose ]; then
        command docker "$@"; return $?
    fi
    case "$2" in
        up|restart|start|stop|rm|down)
            # only gate when the service is exactly nzbdav/nzbdav_rclone
            # (only the active nzbdav services are gated)
            local _svc_hit=false
            local _a2
            for _a2 in "$@"; do
                case "$_a2" in nzbdav|nzbdav_rclone) _svc_hit=true ;; esac
            done
            if [ "$_svc_hit" = true ]; then
                case " $* " in
                    *" --force "*)
                        echo "[guard] --force: skipping queue guard (queued NZBs WILL be wiped)" >&2
                        # strip --force before forwarding (compose doesn't know it)
                        local _args=()
                        local _a
                        for _a in "$@"; do [ "$_a" != --force ] && _args+=("$_a"); done
                        command docker "${_args[@]}"
                        return $?
                        ;;
                    *)
                        guard="${BEARCAVE_REPO_DIR:-$HOME/TheBearCave}/scripts/nzbdav-safe-recreate.sh"
                        if [ -x "$guard" ]; then
                            shift  # drop the leading `docker`
                            bash "$guard" "$@"
                            return $?
                        fi
                        echo "[guard] nzbdav-safe-recreate.sh not found — running unguarded" >&2
                        command docker "$@"
                        return $?
                        ;;
                esac
            fi
            ;;
    esac
    command docker "$@"; return $?
}
SNIPPET
echo "Wrote bash/zsh docker-guard snippet to $BASH_SNIPPET_DIR/docker-guard.sh"
echo "  Source it from ~/.bashrc or ~/.zshrc:"
echo "    source $BASH_SNIPPET_DIR/docker-guard.sh"

# ----------------------------------------------------------------------------
# Verification: the installed symlink set must resolve, and stack-help must run
# clean in a fresh shell. A dangling link here means an install bug or an
# ephemeral source checkout; a noisy stack-help means broken description
# lookups. Fail loudly instead of leaving a silently broken install.
# ----------------------------------------------------------------------------
verify_failed=0
for d in functions completions conf.d; do
    while IFS= read -r link; do
        [ -z "$link" ] && continue
        echo "  FAIL: dangling symlink: $link -> $(readlink "$link")" >&2
        verify_failed=$((verify_failed + 1))
    done < <(find "$FISH_DIR/$d" -maxdepth 1 -type l ! -exec test -e {} \; -print 2>/dev/null)
done

help_out="$(timeout 20 fish -c 'stack-help' 2>&1 || true)"
if ! printf '%s\n' "$help_out" | grep -q 'Bear Cave media stack'; then
    echo "  FAIL: stack-help did not run in a fresh shell (is fish installed?)" >&2
    verify_failed=$((verify_failed + 1))
elif printf '%s\n' "$help_out" | grep -q 'No such file or directory'; then
    echo "  FAIL: stack-help reports missing files (dangling function symlinks?)" >&2
    verify_failed=$((verify_failed + 1))
fi

if [ "$verify_failed" -gt 0 ]; then
    echo "" >&2
    echo "ERROR: install verification failed ($verify_failed problem(s))." >&2
    echo "  Installed from: $SCRIPT_DIR" >&2
    exit 1
fi
echo "Verification OK: all installed symlinks resolve and stack-help runs clean."
