#!/usr/bin/env bash
# ============================================================================
# gen-bash-completions.sh — generate bash tab-completions for stack-* commands
# ============================================================================
# Scans services/bash-functions/functions/stack-*.sh for:
#   - function definitions:   stack-<name>() {
#   - completion directives:  # complete: <group1>|<alt> <group2> ... [--flags]
#
# Directive syntax (one per function, anywhere in the file after/around it —
# the directive binds to the most recently seen function definition):
#   # complete: radarr|sonarr|all on|off
#   # complete: -y|--yes
#   # complete: <container>            (dynamic: docker ps -a names)
#   # complete: <arr-app>              (dynamic: radarr sonarr prowlarr)
#
# Groups are positional: group N completes argument N. Groups starting with
# '-' are flag groups offered at any position. '<name>' in angle brackets is
# a dynamic source.
#
# Output: services/bash-functions/completions/stack-completions.sh
#   --check: regenerate to temp and diff; exit 1 if out of date.
#
# Usage:
#   services/bash-functions/scripts/gen-bash-completions.sh            # write
#   services/bash-functions/scripts/gen-bash-completions.sh --check    # verify
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FN_DIR="$(cd "$SCRIPT_DIR/../functions" && pwd)"
OUT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/completions"
OUT_FILE="$OUT_DIR/stack-completions.sh"
CHECK=false
[ "${1:-}" = "--check" ] && CHECK=true

mkdir -p "$OUT_DIR"

# ----------------------------------------------------------------------------
# Collect function definitions and directives
# ----------------------------------------------------------------------------
declare -A CMDS      # name -> 1
declare -A DIRECTIVE # name -> raw directive args

current_fn=""
for f in "$FN_DIR"/stack-*.sh; do
    [ -f "$f" ] || continue
    while IFS= read -r line; do
        if [[ "$line" =~ ^(stack-[a-z0-9-]+)\(\)\ \{ ]]; then
            current_fn="${BASH_REMATCH[1]}"
            CMDS["$current_fn"]=1
        elif [[ "$line" =~ ^#\ complete:\ (.+)$ ]] && [ -n "$current_fn" ]; then
            DIRECTIVE["$current_fn"]="${BASH_REMATCH[1]}"
        fi
    done < "$f"
done

if [ "${#CMDS[@]}" -eq 0 ]; then
    echo "ERROR: no stack-* functions found in $FN_DIR" >&2
    exit 1
fi

# ----------------------------------------------------------------------------
# Build the generated completion file
# ----------------------------------------------------------------------------
TMP="$(mktemp)"
{
    cat <<'HDR'
# ============================================================================
# stack-completions.sh — GENERATED by gen-bash-completions.sh — do not edit
# ============================================================================
# Regenerate:  services/bash-functions/scripts/gen-bash-completions.sh
# Verify:      services/bash-functions/scripts/gen-bash-completions.sh --check
# Loaded automatically by bearcave-bash.sh (services/bash-functions/).
# ============================================================================
# shellcheck disable=SC2207

__stack_complete() {
    local cur cmd pos
    cur="${COMP_WORDS[COMP_CWORD]}"
    cmd="${COMP_WORDS[0]}"
    pos=$((COMP_CWORD - 1))   # 0-based index of the word being completed

    # Dynamic sources
    local CONTAINERS
    CONTAINERS=$(docker ps -a --format '{{.Names}}' 2>/dev/null | sort)
    local ARR_APPS="radarr sonarr prowlarr"
    local BUTLER_TASKS="clean-updates optimize-database refresh-local-media\n    backup-database garbage-collect-blobs garbage-collect-media\n    clean-cache-files clean-log-files process-assets generate-media-index\n    deep-media-analysis upgrade-media-analysis music-analysis\n    loudness-analysis generate-intro-markers generate-credits-markers\n    generate-ad-markers generate-chapter-thumbs generate-voice-activity\n    refresh-epg refresh-libraries automatic-updates"
    BUTLER_TASKS=$(printf '%b' "$BUTLER_TASKS" | tr '\n' ' ')

    case "$cmd" in
HDR

    for fn in $(printf '%s\n' "${!CMDS[@]}" | sort); do
        echo "        $fn)"
        spec="${DIRECTIVE[$fn]:-}"
        if [ -z "$spec" ]; then
            echo "            ;;"
            continue
        fi
        read -r -a groups <<< "$spec"
        flags=""
        gi=0
        for g in "${groups[@]}"; do
            case "$g" in
                -*)
                    # flag group: split alternates (-y|--yes -> -y --yes)
                    fwords="${g//|/ }"
                    flags="$flags $fwords"
                    ;;
                '<container>')
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "$CONTAINERS" -- "$cur")); return 0; fi\n' "$((gi + 1))"
                    gi=$((gi + 1))
                    ;;
                '<arr-app>')
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "$ARR_APPS" -- "$cur")); return 0; fi\n' "$((gi + 1))"
                    gi=$((gi + 1))
                    ;;
                '<butler-task>')
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "$BUTLER_TASKS" -- "$cur")); return 0; fi\n' "$((gi + 1))"
                    gi=$((gi + 1))
                    ;;
                *)
                    words="${g//|/ }"
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "%s" -- "$cur")); return 0; fi\n' "$((gi + 1))" "$words"
                    gi=$((gi + 1))
                    ;;
            esac
        done
        if [ -n "$flags" ]; then
            printf '            COMPREPLY=($(compgen -W "%s" -- "$cur")); return 0;\n' "$flags"
        fi
        if [ -n "$flags" ] || [ "$gi" -gt 0 ]; then
            echo "            return 0;"
        fi
        echo "            ;;"
    done

    cat <<'FTR'
    esac

    # Unknown command (no directive branch matched) — offer command names.
    COMPREPLY=($(compgen -W "__ALL_CMDS__" -- "$cur"))
}

complete -F __stack_complete -o bashdefault -o default -o nospace __STACK_CMDS__
FTR
} > "$TMP"

# Substitute the command list into the footer (kept out of the heredoc so the
# generator never has to escape the list).
ALL_CMDS="$(printf '%s\n' "${!CMDS[@]}" | sort | tr '\n' ' ' | sed 's/ $//')"
sed -i "s/__ALL_CMDS__/${ALL_CMDS//&/\\&}/" "$TMP"
sed -i "s/__STACK_CMDS__/${ALL_CMDS//&/\\&}/" "$TMP"

# ----------------------------------------------------------------------------
# Write or verify
# ----------------------------------------------------------------------------
if [ "$CHECK" = true ]; then
    if [ ! -f "$OUT_FILE" ]; then
        echo "FAIL: $OUT_FILE missing — run gen-bash-completions.sh to generate it." >&2
        rm -f "$TMP"
        exit 1
    fi
    if ! diff -q "$TMP" "$OUT_FILE" >/dev/null 2>&1; then
        echo "FAIL: $OUT_FILE is out of date with the function files." >&2
        echo "  Regenerate: services/bash-functions/scripts/gen-bash-completions.sh" >&2
        rm -f "$TMP"
        exit 1
    fi
    echo "OK: $OUT_FILE is current."
else
    mv "$TMP" "$OUT_FILE"
    echo "Wrote $OUT_FILE ($(wc -l < "$OUT_FILE") lines, ${#CMDS[@]} commands)."
fi
