#!/usr/bin/env python3
"""Remediate Sonarr DB bloat (AGENTS.md landmine #9): backup, prune, VACUUM, verify.

Sonarr analogue of scripts/prune_radarr_db.py. The companion check
(scripts/check_radarr_db_size.py with --blob-table EpisodeFiles) only DETECTS
the bloat; this script REMEDIATES it. The 2026-09-02 maintenance-digest sweep
found the first instance live: a 3.2 GiB sonarr.db with ~2.0 GiB sitting in
EpisodeFiles.MediaInfo alone — the exact class of bloat that OOMed radarr at a
1 GB radarr.db. Run after the check flags the DB, or on a schedule.

Order of operations, each step guarded:
  1. refuse unless the DB can be located and read (write access required)
  2. integrity-check before touching anything (abort on corruption)
  3. decline to run when the DB is already healthy (--force overrides, e.g.
     to reclaim freelist pages without MediaInfo bloat)
  4. back up sonarr.db (+ logs.db when present) to
     config/sonarr/Backups/manual-maintenance-<timestamp>/
  5. prune: UPDATE EpisodeFiles SET MediaInfo = NULL (regenerated by Sonarr on
     the next library rescan/analyze) + trim History rows older than
     --keep-history-days
  6. VACUUM the freed pages (logs.db Logs table trimmed to the most recent
     --keep-log-rows rows as part of the same pass)
  7. integrity-check again and re-measure; exit 1 if bloat remains

Sonarr must be stopped while this runs — a running process holds the SQLite
lock, so the operation fails with a hint instead of corrupting anything. The
bash wrapper stack-sonarr-prune stops and restarts the container around this
script. Exit codes:
  0  pruned (or nothing was needed)
  1  bloat remains / verification failed / declined / DB locked / corrupt
  2  the Sonarr DB could not be located or read

Usage:
  python3 scripts/prune_sonarr_db.py --yes          # prune with defaults
  SONARR_DB=/path/to/sonarr.db python3 scripts/prune_sonarr_db.py
  python3 scripts/prune_sonarr_db.py --dry-run      # report only, touch nothing
  python3 scripts/prune_sonarr_db.py --yes --keep-history-days 180 --keep-log-rows 1000
"""

import argparse
import os
import shutil
import sqlite3
import sys
import time
from pathlib import Path

import check_radarr_db_size as checker

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DB = ROOT / "config" / "sonarr" / "sonarr.db"
DEFAULT_LOGS_DB = ROOT / "config" / "sonarr" / "logs.db"
BLOB_TABLE = "EpisodeFiles"  # Sonarr's MediaInfo blob table (vs Radarr's MovieFiles)

DEFAULT_KEEP_HISTORY_DAYS = 90   # trim History older than this
DEFAULT_KEEP_LOG_ROWS = 5000     # keep the newest N Logs rows in logs.db


def _mb(n: int) -> str:
    return f"{n / (1024 * 1024):.0f} MiB"


def backup_files(db_path: Path, logs_path, dest_root: Path) -> Path:
    """Copy sonarr.db (+ logs.db when present) into a new timestamped dir.

    Raises OSError on copy failure; the caller aborts before touching the DB.
    """
    stamp = time.strftime("%Y%m%d-%H%M%S")
    dest = dest_root / f"manual-maintenance-{stamp}"
    dest.mkdir(parents=True, exist_ok=True)
    for src in (db_path, logs_path):
        if src is not None and src.is_file():
            shutil.copy2(src, dest / src.name)
    return dest


def prune_sonarr(db_path: Path, logs_path=None,
                 keep_history_days: int = DEFAULT_KEEP_HISTORY_DAYS,
                 keep_log_rows: int = DEFAULT_KEEP_LOG_ROWS) -> None:
    """Prune bloat and VACUUM sonarr.db (+ logs.db). Raises sqlite3.Error on
    lock/corruption — the integrity check runs before any write."""
    con = sqlite3.connect(db_path, timeout=3)
    try:
        con.execute("PRAGMA journal_mode=DELETE")
        has_files = con.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='EpisodeFiles'"
        ).fetchone() is not None
        if has_files:
            con.execute("UPDATE EpisodeFiles SET MediaInfo = NULL")
        has_history = con.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='History'"
        ).fetchone() is not None
        if has_history:
            con.execute(
                "DELETE FROM History WHERE Date < datetime('now', ?)",
                (f"-{int(keep_history_days)} days",),
            )
        con.commit()
        con.execute("VACUUM")
        con.commit()
    finally:
        con.close()

    if logs_path is not None and logs_path.is_file():
        lcon = sqlite3.connect(logs_path, timeout=3)
        try:
            lcon.execute("PRAGMA journal_mode=DELETE")
            has_logs = lcon.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name='Logs'"
            ).fetchone() is not None
            if has_logs:
                lcon.execute(
                    "DELETE FROM Logs WHERE Id NOT IN "
                    "(SELECT Id FROM Logs ORDER BY Id DESC LIMIT ?)",
                    (int(keep_log_rows),),
                )
            lcon.commit()
            lcon.execute("VACUUM")
            lcon.commit()
        finally:
            lcon.close()


def integrity_ok(db_path: Path) -> bool:
    con = sqlite3.connect(db_path, timeout=3)
    try:
        return con.execute("PRAGMA integrity_check").fetchone()[0] == "ok"
    finally:
        con.close()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=os.environ.get("SONARR_DB", str(DEFAULT_DB)))
    ap.add_argument("--logs-db", default=os.environ.get("SONARR_LOGS_DB",
                                                       str(DEFAULT_LOGS_DB)))
    ap.add_argument("--max-footprint", type=float,
                    default=float(os.environ.get("SONARR_MAX_FOOTPRINT_MB",
                                                 checker.DEFAULT_MAX_FOOTPRINT_MB)))
    ap.add_argument("--max-mediainfo", type=float,
                    default=float(os.environ.get("SONARR_MAX_MEDIAINFO_MB",
                                                 checker.DEFAULT_MAX_MEDIAINFO_MB)))
    ap.add_argument("--keep-history-days", type=int, default=DEFAULT_KEEP_HISTORY_DAYS,
                    help="trim History older than this (default: %(default)s)")
    ap.add_argument("--keep-log-rows", type=int, default=DEFAULT_KEEP_LOG_ROWS,
                    help="keep newest N Logs rows in logs.db (default: %(default)s)")
    ap.add_argument("--yes", action="store_true", help="skip the confirmation prompt")
    ap.add_argument("--force", action="store_true",
                    help="prune even when the DB looks healthy (reclaims freelist pages)")
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would be done without touching anything")
    args = ap.parse_args()

    db = Path(args.db)
    logs_db = Path(args.logs_db)
    if not db.is_file():
        print(f"sonarr DB not found at {db}; skipping (set SONARR_DB or --db)")
        return 2

    try:
        m = checker.read_metrics(db, BLOB_TABLE)
    except (sqlite3.Error, OSError) as exc:
        print(f"could not read sonarr DB {db}: {exc}")
        return 2

    max_fp = int(args.max_footprint * 1024 * 1024)
    max_me = int(args.max_mediainfo * 1024 * 1024)
    problems = checker.assess(m["page_size"], m["footprint_bytes"],
                              m["media_bytes"], max_fp, max_me,
                              db_name="sonarr.db", blob_table=BLOB_TABLE)

    print(f"page_size={m['page_size']} page_count={m['page_count']} "
          f"freelist={m['freelist']} footprint={_mb(m['footprint_bytes'])} "
          f"mediainfo={_mb(m['media_bytes'])}")

    if not problems and not args.force:
        print("OK: no bloat detected; nothing to prune "
              "(use --force to VACUUM anyway and reclaim freelist pages).")
        return 0

    action = "VACUUM (bloat: none, --force)" if not problems else (
        "prune MediaInfo blobs + trim history + VACUUM")
    if args.dry_run:
        print(f"DRY RUN: would {action} — no changes made.")
        return 0

    if not args.yes:
        print(f"Plan: {action}. This rewrites sonarr.db and removes MediaInfo "
              "metadata (regenerated on rescan) and trimmed history.")
        confirmed = input("Proceed? [y/N] ").strip().lower() in ("y", "yes")
        if not confirmed:
            print("Declined; nothing was changed.")
            return 1

    # Guard: never touch a corrupt DB, and never leave bloat behind.
    if not integrity_ok(db):
        print("CHECK FAILED: sonarr.db failed PRAGMA integrity_check before "
              "prune; stopping (restore from a backup and re-run).")
        return 1

    backup_root = db.parent / "Backups"
    try:
        dest = backup_files(db, logs_db, backup_root)
        print(f"backup: {dest}")
    except OSError as exc:
        print(f"CHECK FAILED: could not back up sonarr DB: {exc}")
        return 1

    try:
        prune_sonarr(db, logs_db, args.keep_history_days, args.keep_log_rows)
    except sqlite3.OperationalError as exc:
        if "locked" in str(exc).lower():
            print("CHECK FAILED: sonarr.db is locked — stop sonarr first "
                  "(docker compose stop sonarr) and re-run.")
        else:
            print(f"CHECK FAILED: prune failed: {exc}")
        return 1
    except sqlite3.Error as exc:
        print(f"CHECK FAILED: prune failed: {exc}")
        return 1

    if not integrity_ok(db):
        print("CHECK FAILED: sonarr.db failed PRAGMA integrity_check after "
              "prune — restore from backup and investigate.")
        return 1

    post = checker.read_metrics(db, BLOB_TABLE)
    remaining = checker.assess(post["page_size"], post["footprint_bytes"],
                               post["media_bytes"], max_fp, max_me,
                               db_name="sonarr.db", blob_table=BLOB_TABLE)
    print(f"after: page_count={post['page_count']} freelist={post['freelist']} "
          f"footprint={_mb(post['footprint_bytes'])} "
          f"mediainfo={_mb(post['media_bytes'])}")
    if remaining:
        for p in remaining:
            print(f"  BLOAT: {p}")
        print(f"CHECK FAILED: bloat remains after prune ({len(remaining)} problem(s)).")
        return 1

    print(f"VERIFIED: {_mb(m['footprint_bytes'])} -> "
          f"{_mb(post['footprint_bytes'])}; integrity ok.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
